openapi: 3.0.0
info:
  title: RAG Chatbot API
  description: API for the RAG Chatbot embedded in Docusaurus book
  version: 1.0.0
servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://your-backend-domain.com
    description: Production server

paths:
  /chat:
    post:
      summary: Send a message and receive a response
      description: Process a user message and return an AI-generated response based on book content
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MessageRequest'
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MessageResponse'
        '400':
          description: Bad request - invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /conversations/{conversation_id}:
    get:
      summary: Get conversation history
      description: Retrieve the history of messages for a specific conversation
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            example: "conv_abc123"
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversationResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: Delete a conversation
      description: Remove a conversation and all its messages
      parameters:
        - name: conversation_id
          in: path
          required: true
          schema:
            type: string
            example: "conv_abc123"
      responses:
        '200':
          description: Conversation deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '404':
          description: Conversation not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /documents/ingest:
    post:
      summary: Ingest a document
      description: Process and store a document for RAG retrieval
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DocumentIngestRequest'
      responses:
        '200':
          description: Document ingested successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StatusResponse'
        '400':
          description: Bad request - invalid document data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      summary: Health check
      description: Check if the service is running and healthy
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    MessageRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          description: The user's message
          example: "What is this book about?"
        conversation_id:
          type: string
          description: Optional conversation ID to continue an existing conversation
          example: "conv_abc123"
        selected_text:
          type: string
          description: Optional selected text to restrict the response context
          example: "This is the specific text the user selected for focused answers"

    MessageResponse:
      type: object
      required:
        - response
        - conversation_id
      properties:
        response:
          type: string
          description: The AI-generated response
          example: "This book is about building RAG chatbots for Docusaurus documentation..."
        conversation_id:
          type: string
          description: The conversation ID (newly created or existing)
          example: "conv_abc123"
        sources:
          type: array
          items:
            type: string
          description: List of sources referenced in the response
          example: ["/introduction", "/chapter-1/overview"]

    ConversationResponse:
      type: object
      required:
        - conversation_id
        - messages
      properties:
        conversation_id:
          type: string
          description: The conversation ID
          example: "conv_abc123"
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'

    Message:
      type: object
      required:
        - message_id
        - role
        - content
        - timestamp
      properties:
        message_id:
          type: string
          description: Unique identifier for the message
          example: "msg_def456"
        role:
          type: string
          enum: [user, assistant]
          description: The role of the message sender
          example: "user"
        content:
          type: string
          description: The message content
          example: "What is this book about?"
        timestamp:
          type: string
          format: date-time
          description: When the message was created
          example: "2023-10-20T10:00:00Z"
        sources:
          type: array
          items:
            type: string
          description: Sources referenced in the response (for assistant messages)
        selected_text:
          type: string
          description: Text selected by user when message was sent (for user messages)

    DocumentIngestRequest:
      type: object
      required:
        - source_path
        - content
      properties:
        source_path:
          type: string
          description: Path to the original document
          example: "/docs/introduction.md"
        content:
          type: string
          description: The document content
          example: "# Introduction\nThis book teaches you how to..."
        metadata:
          type: object
          description: Additional metadata about the document
          example: {"title": "Introduction", "section": "Overview"}

    StatusResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: Status message
          example: "success"

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
          example: "Invalid input parameters"
        details:
          type: string
          description: Additional error details (optional)
          example: "Message field is required"

    HealthResponse:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          description: Health status
          example: "healthy"